fastlane_version '2.151.2'

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
   desc 'Fetch certificates and provisioning profiles'
   lane :certificates do
     match(app_identifier: 'com.labiba.app', type: 'appstore', readonly: false)
   end

   desc 'Build the iOS application.'
   private_lane :build do
     certificates
     increment_build_number(xcodeproj: './ios/Optonome.xcodeproj')
#     xcarchive(scheme: 'Labiba', workspace: './ios/Labiba.xcworkspace')
      build_app(scheme: 'Labiba', workspace: './ios/Labiba.xcworkspace', output_directory: './Build', output_name: 'Labiba.ipa', include_bitcode: true)
   end

   desc 'Ship to Testflight.'
   lane :beta do
     build
     pilot(username: 'yan.tao463@hotmail.com')
     commit_version_bump(message: 'Bump build', xcodeproj: './ios/Labiba.xcodeproj')
     push_to_git_remote
   end
end

platform :android do
  # Android Lanes
end
