fastlane_version '2.151.2'

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
   desc 'Fetch certificates and provisioning profiles'
   lane :certificates do
     match(app_identifier: 'org.intelladapt.optonome', type: 'appstore', readonly: false)
   end

   desc 'Build the iOS application.'
   private_lane :build do
     certificates
     increment_build_number(xcodeproj: './ios/Optonome.xcodeproj')
#     xcarchive(scheme: 'Optonome', workspace: './ios/Optonome.xcworkspace')
      build_app(scheme: 'Optonome', workspace: './ios/Optonome.xcworkspace', output_directory: './Build', output_name: 'Optonome.ipa', include_bitcode: true)
   end

   desc 'Ship to Testflight.'
   lane :beta do
     build
     pilot(username: 'sts.dev0488@gmail.com')
     commit_version_bump(message: 'Bump build', xcodeproj: './ios/Optonome.xcodeproj')
     push_to_git_remote
   end
end

platform :android do
  # Android Lanes
end
