export const GET_FAVORITE_LIST = 'GET_FAVORITE_LIST';
export const GET_FAVORITE_LIST_REQUEST = 'GET_FAVORITE_LIST_REQUEST';
export const GET_FAVORITE_LIST_SUCCESS = 'GET_FAVORITE_LIST_SUCCESS';
export const GET_FAVORITE_LIST_ERROR = 'GET_FAVORITE_LIST_ERROR';
export const CREATE_FAVORITE_ITEM = 'CREATE_FAVORITE_ITEM';
export const CREATE_FAVORITE_ITEM_REQUEST = 'CREATE_FAVORITE_ITEM_REQUEST';
export const CREATE_FAVORITE_ITEM_SUCCESS = 'CREATE_FAVORITE_ITEM_SUCCESS';
export const CREATE_FAVORITE_ITEM_ERROR = 'CREATE_FAVORITE_ITEM_ERROR';

export const getFavoriteList = () => ({
  type: GET_FAVORITE_LIST,
});

export const createFavoriteItem = (payload) => ({
  type: CREATE_FAVORITE_ITEM,
  payload,
});
